### ISSUE TITLE
picofeed v1.1 fails with autodetection

### ISSUE THREAD

**Issue by freddii** [seenaburns/picofeed#1]
$ ./picofeed-linux http://seenaburns/
ERROR: Get http://seenaburns/: dial tcp: lookup seenaburns on 127.0.0.53:53: server misbehaving

**Comment by seenaburns** [comment]
This should work if you specify the TLD, like `./picofeed-linux http://seenaburns.com/`, I'm not sure what the expected behavior would be otherwise
